services:
  db-postgres:
    image: postgres:13.3
    container_name: db-postgres
    hostname: db-postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5445:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./source/init_scripts/init_source.sql:/docker-entrypoint-initdb.d/init_source.sql:ro
      # - ./source/source_data:/source_data:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db-clickhouse:
    image: clickhouse/clickhouse-server:24.9.3
    container_name: db-clickhouse
    hostname: db-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./db/clickhouse:/etc/clickhouse-server
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 1m

volumes:
  postgres-data:
  clickhouse-data: