kind: apps/DQ
version: v1
metadata:
  project: test_dq
  name: test_table
  annotations:
    owner: Kaboupi
    description: >-
      Sample DQ script for table `test_table` both in:
        - Postgres
        - Clickhouse
tasks:
  postgres_data:
    version: v0.0.1
    spec:
      asset:
        description: Data from postgres
        connection:
          host: localhost
          port: 5445
          database: postgres_db
          username: postgres_user
          password: postgres_password
        type: postgres
      params:
        type: SQL
        query: >-
          SELECT *
          FROM public.my_table;
        dimDate: sale_date
  clickhouse_data:
    version: v0.0.1
    spec:
      asset:
        description: Data from clickhouse
        connection:
          host: localhost
          port: 8123
          database: default
          username: admin
          password: admin
        type: clickhouse
      params:
        type: SQL
        query: >-
          SELECT *
          FROM default.my_table;
        dimDate: sale_date